//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.AuditLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log_2015
    {
        public int Id { get; set; }
        public string DB { get; set; }
        public string Domain { get; set; }
        public string IPAddress { get; set; }
        public string TableName { get; set; }
        public Nullable<int> AppId { get; set; }
        public string ActionName { get; set; }
        public string ActionType { get; set; }
        public string RecordIds { get; set; }
        public string RecordType { get; set; }
        public string Name { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Username { get; set; }
        public string SessionInfo { get; set; }
        public string Info { get; set; }
        public string DiffInfo { get; set; }
        public Nullable<long> UCompId { get; set; }
        public Nullable<long> UAgentId { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
