//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.Queue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public string TripTime { get; set; }
        public Nullable<int> TripAlias { get; set; }
        public string FromArea { get; set; }
        public string ToArea { get; set; }
        public string SeatCode { get; set; }
        public string PassCode { get; set; }
        public string RoundTripCode { get; set; }
        public Nullable<System.DateTime> FromValid { get; set; }
        public Nullable<System.DateTime> ToValid { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string PickupInfo { get; set; }
        public string DropOffInfo { get; set; }
        public string FacilityInfo { get; set; }
        public string DeliveryInfo { get; set; }
        public string CustomerInfo { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> CancelFee { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string PaymentInfo { get; set; }
        public string TransactionInfo { get; set; }
        public string NotificationInfo { get; set; }
        public string CallerInfo { get; set; }
        public string AgentInfo { get; set; }
        public string UserCharge { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssueInfo { get; set; }
        public string IssuedUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Info { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> IsPrgStatus { get; set; }
        public string IsPrgPartComp { get; set; }
        public Nullable<System.DateTime> IsPrgCreatedDate { get; set; }
        public Nullable<System.DateTime> IsPrgUpdatedDate { get; set; }
        public Nullable<long> IsPrgCreatedUserId { get; set; }
        public Nullable<long> IsPrgUpdatedUserId { get; set; }
        public string IsPrgUnsignKeywords { get; set; }
        public string IsPrgLanguageInfo { get; set; }
        public string IsPrgHistoryInfo { get; set; }
        public Nullable<long> TripId { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> EventId { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<int> StageCode { get; set; }
        public Nullable<int> CancelType { get; set; }
        public string CancelInfo { get; set; }
        public Nullable<int> SeatType { get; set; }
        public string CanceledUser { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public Nullable<int> CanceledAgentId { get; set; }
        public Nullable<int> TimeCode { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public Nullable<int> FromId { get; set; }
        public Nullable<int> ToId { get; set; }
        public Nullable<System.DateTime> LastMovedDate { get; set; }
        public string VexerePaymentInfo { get; set; }
        public Nullable<int> VexerePaymentType { get; set; }
        public string ReturnCode { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string SNote { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string ResponsibilityUser { get; set; }
        public string PickOrReturnDate { get; set; }
        public Nullable<int> XMigrate { get; set; }
        public Nullable<System.DateTime> XMigrateDate { get; set; }
        public Nullable<int> XMigrateKey { get; set; }
        public byte[] IsPrgVersion { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public string BookingCode { get; set; }
        public Nullable<int> XMigrateType { get; set; }
        public Nullable<int> LastMovedTrip { get; set; }
        public Nullable<int> NumOfSend { get; set; }
        public string FirstUserUpdated { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
