using System.Collections.Generic;

namespace Vxr.Bms.Api.Dic
{
    public class D
    {
        public static Dictionary<string, Dictionary<string, string>> _apiParams = new Dictionary<string, Dictionary<string, string>>
        {
            {"Ticket", new Dictionary<string, string>
            {
                {"Id" , "id"},
                {"CompId", "company_id" },
                {"TripId", "trip_id" },
                {"AgentId", "agent_id" },
                {"EventId", "event_id" },
                {"CustomerId", "customer_id" },
                {"Type", "type" },
                {"Code", "code" },
                {"Serial", "serial" },
                {"PassCode", "pass_code" },
                {"RoundTripCode", "route_trip_code" },
                {"TripAlias", "trip_alias" },
                {"TripDate", "date" },
                {"TripTime", "time" },
                {"FromArea", "from_area" },
                {"ToArea", "to_area" },
                {"SeatCode", "seat" },
                {"IssueDate", "issue_date" },
                {"PickupDate", "pickup_date" },
                {"CallerInfo", "caller_info" },
                {"AgentInfo", "agent_info" },
                {"CustomerInfo", "customer" },
                {"UserCharge", "user_charge" },
                {"PickupInfo", "pickup_info" },
                {"DropOffInfo", "drop_off_info" },
                {"PaymentInfo", "payment_info" },
                {"TransactionInfo", "transaction_info" },
                {"NotificationInfo", "notification_info" },
                {"DeliveryInfo", "delivery_info" },
                {"FacilityInfo", "facility" },
                {"IssueInfo", "issue_info" },
                {"Keywords", "keywords" },
                {"Status", "status" },
                {"Note", "note" },
                {"Fare", "fare" },
                {"Debt", "debt" },
                {"Refund", "refund" },
                {"Deposit", "deposit" },
                {"Discount", "discount" },
                {"Surcharge", "surcharge" },
                {"CancelFee", "cancel_fee" },
                {"Commission", "commission" },
                {"Info", "info" },
                {"CreatedUser", "created_user" },
                {"IssuedUser", "issued_user" },
                {"IsPrgStatus", "prg_status" },
                {"IsPrgPartComp", "prg_part_comp" },
                {"IsPrgHistoryInfo", "prg_history" },
                {"IsPrgCreatedDate", "prg_created_date" },
                {"IsPrgUpdatedDate", "prg_updated_date" },
                {"IsPrgUnsignKeywords", "prg_unsign_keywords" },
                {"FromValid", "from_valid" },
                {"ToValid", "to_valid" },
                {"IsPrgCreatedUserId", "prg_created_user_id" },
                {"IsPrgUpdatedUserId", "prg_updated_user_id" },
                {"ChargeDate", "charge_date" },
                {"StageCode", "stage_code" },
                {"CancelType", "cancel_type" },
                {"CancelInfo", "cancel_info" },
                {"SeatType", "seat_type" },
                {"CanceledUser", "canceled_user" },
                {"CanceledDate", "canceled_date" },
                {"CanceledAgentId", "canceled_agent_id" },
                {"TimeCode", "time_code" },
                {"ExpiredTime", "expired_time" },
                {"FromId", "from_id" },
                {"ToId", "to_id" },
                {"LastMovedDate", "last_moved_date" },
                {"LastMovedTrip", "last_moved_trip" },
                {"VexerePaymentInfo", "vxr_payment_info"  },
                {"VexerePaymentType", "vxr_payment_type" },
                {"ReturnDate", "return_date" },
                {"ReturnCode", "return_code" },
                {"SNote", "snote" },
                {"IsConfirmed", "is_confirmed" },
                {"ResponsibilityUser", "responsibility_user" },
                {"PickOrReturnDate", "pick_or_return_date" },
                {"BookingCode", "booking_code" },
                {"DiscountType", "discount_type" },
                {"FinalPrice", "final_price" },
                {"FirstUserUpdated", "first_user_updated" },
                {"NumOfSend", "num_of_send" },
                {"HasSendSms", "has_send_sms" },
                {"PrintStatus", "print_status" },
                {"FromStop", "from_stop" },
                {"ToStop", "to_stop" },
                {"NumOfPrint", "num_of_print" },
            }},
        };
    }
}
