ALTER TABLE Ticket
ADD PrintStatus INT NOT NULL DEFAULT(1)
GO

ALTER TABLE Ticket
ADD NumOfPrint INT NOT NULL DEFAULT(0)
GO

ALTER TABLE Ticket
ADD FromStop NVARCHAR(MAX)
GO

ALTER TABLE Ticket
ADD ToStop NVARCHAR(MAX)
GO