//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.Queue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Trip1 = new HashSet<Trip>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> Alias { get; set; }
        public string LicensePlate { get; set; }
        public string FromArea { get; set; }
        public string ToArea { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<System.DateTime> RealDepartureTime { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> TotalExtendedSeats { get; set; }
        public string OwnerInfo { get; set; }
        public string RouteInfo { get; set; }
        public string PickedPointsInfo { get; set; }
        public string TeamInfo { get; set; }
        public string VehicleInfo { get; set; }
        public string FareInfo { get; set; }
        public string FacilityInfo { get; set; }
        public string SeatFacilityInfo { get; set; }
        public string SeatPolicyInfo { get; set; }
        public string SeatTemplateInfo { get; set; }
        public string ExtendedSeatsInfo { get; set; }
        public Nullable<int> SeatSummaryInfo { get; set; }
        public Nullable<int> StatusInfo { get; set; }
        public string FeeInfo { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public string PayInfo { get; set; }
        public Nullable<long> RevenuesInfo { get; set; }
        public string RightsInfo { get; set; }
        public Nullable<bool> IsVeXeReFull { get; set; }
        public string Info { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> IsPrgStatus { get; set; }
        public string IsPrgPartComp { get; set; }
        public Nullable<System.DateTime> IsPrgCreatedDate { get; set; }
        public Nullable<System.DateTime> IsPrgUpdatedDate { get; set; }
        public Nullable<long> IsPrgCreatedUserId { get; set; }
        public Nullable<long> IsPrgUpdatedUserId { get; set; }
        public string IsPrgUnsignKeywords { get; set; }
        public string IsPrgLanguageInfo { get; set; }
        public string IsPrgHistoryInfo { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<long> BaseId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> EventId { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<int> ExtendedSeatSummaryInfo { get; set; }
        public Nullable<int> ClosedStatus { get; set; }
        public string PassengerMoney { get; set; }
        public string ProductMoney { get; set; }
        public string FeeMoney { get; set; }
        public string BranchReceiveProduct { get; set; }
        public Nullable<int> TotalStage { get; set; }
        public Nullable<long> FromId { get; set; }
        public Nullable<long> ToId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> TotalBookedSeats { get; set; }
        public Nullable<int> TotalPaidSeats { get; set; }
        public string TransferPointsInfo { get; set; }
        public Nullable<int> Discount { get; set; }
        public string NewFare { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> TotalMinutes { get; set; }
        public Nullable<int> TotalDistance { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string VxrFareInfo { get; set; }
        public Nullable<int> VxrDiscount { get; set; }
        public Nullable<int> XModelType { get; set; }
        public Nullable<long> XFareByStageId { get; set; }
        public Nullable<long> XFareTplEffId { get; set; }
        public Nullable<long> RootId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> BookingDays { get; set; }
        public Nullable<int> ExpiredDays { get; set; }
        public Nullable<long> XSeatTemplateId { get; set; }
        public Nullable<long> XVehicleTypeId { get; set; }
        public Nullable<long> XFareTemplateId { get; set; }
        public Nullable<long> XScheduleId { get; set; }
        public Nullable<System.DateTime> XFromDate { get; set; }
        public Nullable<System.DateTime> XToDate { get; set; }
        public string BoardingTimeInfo { get; set; }
        public string PaymentConfig { get; set; }
        public Nullable<int> XMigrate { get; set; }
        public Nullable<System.DateTime> XMigrateDate { get; set; }
        public Nullable<int> XMigrateKey { get; set; }
        public byte[] IsPrgVersion { get; set; }
        public Nullable<int> XMigrateType { get; set; }
        public Nullable<int> VBookingConfig { get; set; }
        public Nullable<int> VPaymentConfig { get; set; }
        public Nullable<int> VAppConfig { get; set; }
        public string FromKeyWords { get; set; }
        public string ToKeywords { get; set; }
        public string MidKeywords { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Trip> Trip1 { get; set; }
        public virtual Trip Trip2 { get; set; }
    }
}
