//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.ServiceSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSMS.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/About", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string About();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/About", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AboutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckClient(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckClient", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckClientAsync(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientInfo(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetClientInfoAsync(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSPro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSPro(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSPro", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSProAsync(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToListMobilePhonePro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSToListMobilePhonePro(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToListMobilePhonePro", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSToListMobilePhoneProAsync(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMS(string clientNo, string clientPass, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSAsync(string clientNo, string clientPass, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMaskedSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMaskedSMS(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMaskedSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMaskedSMSAsync(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToListMobilePhone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSToListMobilePhone(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToListMobilePhone", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSToListMobilePhoneAsync(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToMultiMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSToMultiMessage(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToMultiMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSToMultiMessageAsync(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToMultiMessage_WithoutSplit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSToMultiMessage_WithoutSplit(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSToMultiMessage_WithoutSplit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSToMultiMessage_WithoutSplitAsync(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommingSMSListFromID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCommingSMSListFromID(string clientNo, string clientPass, long fromID, int serviceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommingSMSListFromID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCommingSMSListFromIDAsync(string clientNo, string clientPass, long fromID, int serviceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPageOfCommingSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetTotalPageOfCommingSMS(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPageOfCommingSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetTotalPageOfCommingSMSAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommingSMSListOfPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCommingSMSListOfPage(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommingSMSListOfPage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCommingSMSListOfPageAsync(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientCommingSMSNotDividePage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientCommingSMSNotDividePage(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientCommingSMSNotDividePage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetClientCommingSMSNotDividePageAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientBalance(string clientNo, string clientPass, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetClientBalanceAsync(string clientNo, string clientPass, int serviceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListSMSHostingPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetListSMSHostingPrice(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListSMSHostingPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetListSMSHostingPriceAsync(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSMSStatus(string clientNo, string clientPass, string smsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSMSStatusAsync(string clientNo, string clientPass, string smsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListSMSHostingWithBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetListSMSHostingWithBalance(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListSMSHostingWithBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetListSMSHostingWithBalanceAsync(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatusAttachPhoneNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSMSStatusAttachPhoneNumber(string clientNo, string clientPass, string smsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatusAttachPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSMSStatusAttachPhoneNumberAsync(string clientNo, string clientPass, string smsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientSenderNameList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientSenderNameList(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientSenderNameList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetClientSenderNameListAsync(string clientNo, string clientPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPageOfClientSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetTotalPageOfClientSMS(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPageOfClientSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetTotalPageOfClientSMSAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientSMSListOfPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientSMSListOfPage(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientSMSListOfPage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetClientSMSListOfPageAsync(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Vxr.Bms.ServiceSMS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Vxr.Bms.ServiceSMS.ServiceSoap>, Vxr.Bms.ServiceSMS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string About() {
            return base.Channel.About();
        }
        
        public System.Threading.Tasks.Task<string> AboutAsync() {
            return base.Channel.AboutAsync();
        }
        
        public string CheckClient(string clientNo, string clientPass) {
            return base.Channel.CheckClient(clientNo, clientPass);
        }
        
        public System.Threading.Tasks.Task<string> CheckClientAsync(string clientNo, string clientPass) {
            return base.Channel.CheckClientAsync(clientNo, clientPass);
        }
        
        public string GetClientInfo(string clientNo, string clientPass) {
            return base.Channel.GetClientInfo(clientNo, clientPass);
        }
        
        public System.Threading.Tasks.Task<string> GetClientInfoAsync(string clientNo, string clientPass) {
            return base.Channel.GetClientInfoAsync(clientNo, clientPass);
        }
        
        public string SendSMSPro(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendSMSPro(clientNo, clientPass, senderName, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSProAsync(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendSMSProAsync(clientNo, clientPass, senderName, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public string SendSMSToListMobilePhonePro(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType) {
            return base.Channel.SendSMSToListMobilePhonePro(clientNo, clientPass, senderName, smsContent, listPhoneNumber, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSToListMobilePhoneProAsync(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType) {
            return base.Channel.SendSMSToListMobilePhoneProAsync(clientNo, clientPass, senderName, smsContent, listPhoneNumber, serviceType);
        }
        
        public string SendSMS(string clientNo, string clientPass, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendSMS(clientNo, clientPass, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSAsync(string clientNo, string clientPass, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendSMSAsync(clientNo, clientPass, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public string SendMaskedSMS(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendMaskedSMS(clientNo, clientPass, senderName, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendMaskedSMSAsync(string clientNo, string clientPass, string senderName, string phoneNumber, string smsMessage, string smsGUID, int serviceType) {
            return base.Channel.SendMaskedSMSAsync(clientNo, clientPass, senderName, phoneNumber, smsMessage, smsGUID, serviceType);
        }
        
        public string SendSMSToListMobilePhone(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType) {
            return base.Channel.SendSMSToListMobilePhone(clientNo, clientPass, senderName, smsContent, listPhoneNumber, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSToListMobilePhoneAsync(string clientNo, string clientPass, string senderName, string smsContent, string listPhoneNumber, int serviceType) {
            return base.Channel.SendSMSToListMobilePhoneAsync(clientNo, clientPass, senderName, smsContent, listPhoneNumber, serviceType);
        }
        
        public string SendSMSToMultiMessage(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType) {
            return base.Channel.SendSMSToMultiMessage(clientNo, clientPass, senderName, smsMessage, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSToMultiMessageAsync(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType) {
            return base.Channel.SendSMSToMultiMessageAsync(clientNo, clientPass, senderName, smsMessage, serviceType);
        }
        
        public string SendSMSToMultiMessage_WithoutSplit(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType) {
            return base.Channel.SendSMSToMultiMessage_WithoutSplit(clientNo, clientPass, senderName, smsMessage, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSToMultiMessage_WithoutSplitAsync(string clientNo, string clientPass, string senderName, string smsMessage, int serviceType) {
            return base.Channel.SendSMSToMultiMessage_WithoutSplitAsync(clientNo, clientPass, senderName, smsMessage, serviceType);
        }
        
        public string GetCommingSMSListFromID(string clientNo, string clientPass, long fromID, int serviceTypeID) {
            return base.Channel.GetCommingSMSListFromID(clientNo, clientPass, fromID, serviceTypeID);
        }
        
        public System.Threading.Tasks.Task<string> GetCommingSMSListFromIDAsync(string clientNo, string clientPass, long fromID, int serviceTypeID) {
            return base.Channel.GetCommingSMSListFromIDAsync(clientNo, clientPass, fromID, serviceTypeID);
        }
        
        public int GetTotalPageOfCommingSMS(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetTotalPageOfCommingSMS(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalPageOfCommingSMSAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetTotalPageOfCommingSMSAsync(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public string GetCommingSMSListOfPage(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetCommingSMSListOfPage(clientNo, clientPass, pageNO, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public System.Threading.Tasks.Task<string> GetCommingSMSListOfPageAsync(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetCommingSMSListOfPageAsync(clientNo, clientPass, pageNO, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public string GetClientCommingSMSNotDividePage(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetClientCommingSMSNotDividePage(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public System.Threading.Tasks.Task<string> GetClientCommingSMSNotDividePageAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetClientCommingSMSNotDividePageAsync(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public string GetClientBalance(string clientNo, string clientPass, int serviceType) {
            return base.Channel.GetClientBalance(clientNo, clientPass, serviceType);
        }
        
        public System.Threading.Tasks.Task<string> GetClientBalanceAsync(string clientNo, string clientPass, int serviceType) {
            return base.Channel.GetClientBalanceAsync(clientNo, clientPass, serviceType);
        }
        
        public string GetListSMSHostingPrice(string clientNo, string clientPass) {
            return base.Channel.GetListSMSHostingPrice(clientNo, clientPass);
        }
        
        public System.Threading.Tasks.Task<string> GetListSMSHostingPriceAsync(string clientNo, string clientPass) {
            return base.Channel.GetListSMSHostingPriceAsync(clientNo, clientPass);
        }
        
        public string GetSMSStatus(string clientNo, string clientPass, string smsList) {
            return base.Channel.GetSMSStatus(clientNo, clientPass, smsList);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSStatusAsync(string clientNo, string clientPass, string smsList) {
            return base.Channel.GetSMSStatusAsync(clientNo, clientPass, smsList);
        }
        
        public string GetListSMSHostingWithBalance(string clientNo, string clientPass) {
            return base.Channel.GetListSMSHostingWithBalance(clientNo, clientPass);
        }
        
        public System.Threading.Tasks.Task<string> GetListSMSHostingWithBalanceAsync(string clientNo, string clientPass) {
            return base.Channel.GetListSMSHostingWithBalanceAsync(clientNo, clientPass);
        }
        
        public string GetSMSStatusAttachPhoneNumber(string clientNo, string clientPass, string smsList) {
            return base.Channel.GetSMSStatusAttachPhoneNumber(clientNo, clientPass, smsList);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSStatusAttachPhoneNumberAsync(string clientNo, string clientPass, string smsList) {
            return base.Channel.GetSMSStatusAttachPhoneNumberAsync(clientNo, clientPass, smsList);
        }
        
        public string GetClientSenderNameList(string clientNo, string clientPass) {
            return base.Channel.GetClientSenderNameList(clientNo, clientPass);
        }
        
        public System.Threading.Tasks.Task<string> GetClientSenderNameListAsync(string clientNo, string clientPass) {
            return base.Channel.GetClientSenderNameListAsync(clientNo, clientPass);
        }
        
        public int GetTotalPageOfClientSMS(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetTotalPageOfClientSMS(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalPageOfClientSMSAsync(string clientNo, string clientPass, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetTotalPageOfClientSMSAsync(clientNo, clientPass, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public string GetClientSMSListOfPage(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetClientSMSListOfPage(clientNo, clientPass, pageNO, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
        
        public System.Threading.Tasks.Task<string> GetClientSMSListOfPageAsync(string clientNo, string clientPass, int pageNO, string fromDate, string toDate, string smsStatus, int serviceTypeID, string key) {
            return base.Channel.GetClientSMSListOfPageAsync(clientNo, clientPass, pageNO, fromDate, toDate, smsStatus, serviceTypeID, key);
        }
    }
}
