--- STEP 1: ALTER DB NAME USE MANAGEMENT STUDIO ---

--- STEP 2: ALTER FILE NAME  ---
ALTER DATABASE [VXR_BMS_V03]
            MODIFY FILE (NAME=N'VXR_BMS_003', NEWNAME=N'VXR_BMS_V03')
ALTER DATABASE [VXR_BMS_V03]
            MODIFY FILE (NAME=N'VXR_BMS_003_log', NEWNAME=N'VXR_BMS_V03_log')

--- STEP 3: ALTER FILE PHYSICAL NAME:  DETACH ---

USE [master]
ALTER DATABASE [VXR_BMS_V03]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
EXEC master.dbo.sp_detach_db @dbname = N'VXR_BMS_V03'

--- STEP 4: ALTER FILE PHYSICAL NAME:  CHANGE FILE NAME ---

--- STEP 5: ALTER FILE PHYSICAL NAME:  ATTACH ---
USE [master]
CREATE DATABASE [VXR_BMS_V03] ON
( FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\VXR_BMS_V03.mdf'),
( FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\VXR_BMS_V03_log.ldf')
 FOR ATTACH

 -----------------------

 