//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.Queue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BookingTicket { get; set; }
        public Nullable<decimal> TotalBooking { get; set; }
        public Nullable<int> PaidTicket { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<int> CancelTicket { get; set; }
        public Nullable<decimal> TotalCancel { get; set; }
        public Nullable<int> NotComeTicket { get; set; }
        public Nullable<decimal> TotalNotCome { get; set; }
        public Nullable<int> PassTicket { get; set; }
        public Nullable<decimal> TotalPass { get; set; }
        public Nullable<int> OpenTicket { get; set; }
        public Nullable<decimal> TotalOpen { get; set; }
        public Nullable<int> ValidTicket { get; set; }
        public Nullable<decimal> TotalValid { get; set; }
        public Nullable<int> KeepOnTimeTicket { get; set; }
        public Nullable<decimal> TotalKeepOnTime { get; set; }
        public Nullable<int> TotalTicket { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<long> LastedTripId { get; set; }
        public Nullable<System.DateTime> LastedTripDate { get; set; }
        public string LastedTripTime { get; set; }
        public Nullable<int> LastedTotalTicket { get; set; }
        public Nullable<int> TotalProduct { get; set; }
        public Nullable<decimal> TotalProductMoney { get; set; }
        public Nullable<long> LastedProductTripId { get; set; }
        public Nullable<System.DateTime> LastedProductTripDate { get; set; }
        public string LastedProductTripTime { get; set; }
        public Nullable<int> LastedTotalProduct { get; set; }
        public Nullable<int> TotalProductOrder { get; set; }
        public string Email { get; set; }
        public string VipInfo { get; set; }
        public Nullable<int> Gender { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string AddressInfo { get; set; }
        public string PhoneInfo { get; set; }
        public string FaxInfo { get; set; }
        public string EmailInfo { get; set; }
        public string ImageInfo { get; set; }
        public string WebsiteInfo { get; set; }
        public string URLInfo { get; set; }
        public string BankAccountInfo { get; set; }
        public string LicenseInfo { get; set; }
        public string FamilyInfo { get; set; }
        public string UIConfigInfo { get; set; }
        public string Info { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> IsPrgStatus { get; set; }
        public string IsPrgPartComp { get; set; }
        public Nullable<System.DateTime> IsPrgCreatedDate { get; set; }
        public Nullable<System.DateTime> IsPrgUpdatedDate { get; set; }
        public Nullable<long> IsPrgCreatedUserId { get; set; }
        public Nullable<long> IsPrgUpdatedUserId { get; set; }
        public string IsPrgUnsignKeywords { get; set; }
        public string IsPrgLanguageInfo { get; set; }
        public string IsPrgHistoryInfo { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<int> TotalTrip { get; set; }
        public Nullable<int> TotalCancelTrip { get; set; }
        public Nullable<int> UnpaidProductOrder { get; set; }
        public Nullable<decimal> TotalUnpaidProductOrder { get; set; }
        public Nullable<int> PaidProductOrder { get; set; }
        public Nullable<decimal> TotalPaidProductOrder { get; set; }
        public Nullable<int> UnpaidNotReceivedProductOrder { get; set; }
        public Nullable<decimal> TotalUnpaidNotReceivedProductOrder { get; set; }
        public Nullable<int> UnpaidReceivedProductOrder { get; set; }
        public Nullable<decimal> TotalUnpaidReceivedProductOrder { get; set; }
        public Nullable<int> PaidNotReceivedProductOrder { get; set; }
        public Nullable<decimal> TotalPaidNotReceivedProductOrder { get; set; }
        public Nullable<int> PaidReceivedProductOrder { get; set; }
        public Nullable<decimal> TotalPaidReceivedProductOrder { get; set; }
        public Nullable<int> UnpaidUndeliveredProductOrder { get; set; }
        public Nullable<decimal> TotalUnpaidUndeliveredProductOrder { get; set; }
        public Nullable<int> PaidUndeliveredProductOrder { get; set; }
        public Nullable<decimal> TotalPaidUndeliveredProductOrder { get; set; }
        public Nullable<int> PaidDeliveredProductOrder { get; set; }
        public Nullable<decimal> TotalPaidDeliveredProductOrder { get; set; }
        public Nullable<int> XMigrate { get; set; }
        public Nullable<System.DateTime> XMigrateDate { get; set; }
        public Nullable<int> XMigrateKey { get; set; }
        public byte[] IsPrgVersion { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
