//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vxr.Bms.Queue
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTrip
    {
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TripName { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BookingTicket { get; set; }
        public Nullable<decimal> TotalBooking { get; set; }
        public string ListSeatBooking { get; set; }
        public Nullable<int> PaidTicket { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string ListSeatPaid { get; set; }
        public Nullable<int> CancelTicket { get; set; }
        public Nullable<decimal> TotalCancel { get; set; }
        public string ListSeatCancel { get; set; }
        public Nullable<int> NotComeTicket { get; set; }
        public Nullable<decimal> TotalNotCome { get; set; }
        public string ListSeatNotCome { get; set; }
        public Nullable<int> PassTicket { get; set; }
        public Nullable<decimal> TotalPass { get; set; }
        public string ListSeatPass { get; set; }
        public Nullable<int> KeepOnTimeTicket { get; set; }
        public Nullable<decimal> TotalKeepOnTime { get; set; }
        public string ListSeatKeepOnTime { get; set; }
        public string Email { get; set; }
        public string VipInfo { get; set; }
        public Nullable<int> Gender { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string AddressInfo { get; set; }
        public string PhoneInfo { get; set; }
        public string FaxInfo { get; set; }
        public string EmailInfo { get; set; }
        public string ImageInfo { get; set; }
        public string WebsiteInfo { get; set; }
        public string URLInfo { get; set; }
        public string BankAccountInfo { get; set; }
        public string LicenseInfo { get; set; }
        public string FamilyInfo { get; set; }
        public string UIConfigInfo { get; set; }
        public string Info { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> IsPrgStatus { get; set; }
        public string IsPrgPartComp { get; set; }
        public Nullable<System.DateTime> IsPrgCreatedDate { get; set; }
        public Nullable<System.DateTime> IsPrgUpdatedDate { get; set; }
        public Nullable<long> IsPrgCreatedUserId { get; set; }
        public Nullable<long> IsPrgUpdatedUserId { get; set; }
        public string IsPrgUnsignKeywords { get; set; }
        public string IsPrgLanguageInfo { get; set; }
        public string IsPrgHistoryInfo { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<long> TripId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public string PickupInfo { get; set; }
        public Nullable<int> XMigrate { get; set; }
        public Nullable<System.DateTime> XMigrateDate { get; set; }
        public Nullable<int> XMigrateKey { get; set; }
        public byte[] IsPrgVersion { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
